version: "3.9"
services:
  es01:
    image: elasticsearch:8.6.2
    restart: always
    ports:
      - 9200:9200
    env_file:
      - .env
    volumes:
      - es01:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-network
  kibana:
    image: kibana:8.6.2
    restart: always
    ports:
      - 5601:5601
    depends_on:
      - es01
    networks:
      - es-network

volumes:
  es01:
networks:
  es-network:
    driver: bridge
